### ISSUE TITLE
Write README.md Clearly 

### ISSUE THREAD

**Issue by GalacticGazelle** [Dinujaya-Sandaruwan/simple-AJAX-programme#1]
# Introduction to AJAX
AJAX (Asynchronous JavaScript and XML) is a technique used in web development to create interactive and dynamic web pages. It allows web pages to update content asynchronously, without the need for a full page refresh.

AJAX uses a combination of technologies including HTML, CSS, JavaScript, and XML/JSON. It allows web applications to exchange data with a server in the background, without interrupting the user's interaction with the page.

AJAX has become a popular technique for creating web applications as it provides a smooth and seamless user experience. Web applications that use AJAX can update specific parts of a page without requiring the user to reload the entire page, resulting in faster load times and better performance.

In this guide, we will explore the basics of AJAX and how it works. We will also cover some common use cases for AJAX and provide some examples of how it can be implemented in web development. By the end of this guide, you should have a solid understanding of how AJAX can be used to create dynamic and interactive web pages.

**Comment by Dinujaya-Sandaruwan** [comment]
Thanks ❤️
